### ISSUE TITLE
terraform plan 오류 문의

### ISSUE THREAD

**Issue by leechoongyon** [charsyam/the_red_infra#6]
안녕하세요. 

readme 에 나와있는 대로 진행했는데 

terraform plan -out "output" 에서 에러가 발생했는데요. 인터넷을 찾아봐도 무슨 에러인지 해결을 못해서 질문 드립니다.

에러 로그는 아래와 같습니다. 환경은 M1 mac 에서 진행했습니다.

답변 부탁드립니다. 감사합니다.

```
Error: no matching EC2 VPC found
│ 
│   with data.aws_vpc.default,
│   on vpc.tf line 1, in data "aws_vpc" "default":
│    1: data "aws_vpc" "default" {
```

**Comment by dev-lemontree** [comment]
안녕하세요. 몇 가지 질문드리고 싶은게 있습니다.

1] AWS 는 가입을 하신걸까요?
2] 위의 로그는 다른 내용은 더 없을까요?
3] terraform 버전은 무엇을 사용하고 계실까요?
 m1의 경우 특정 버전 이상을 사용해야만 제대로 돌아가기도 합니다.

**Comment by leechoongyon** [comment]
안녕하세요.

1] AWS 는 가입을 하신걸까요?
--> 네 AWS 가입했고, provider.tf 에 access_key 와 secret_key 를 세팅하니 terraform plan -out "output" 는 넘어갔습니다.

2] 위의 로그는 다른 내용은 더 없을까요?
--> 네 AWS 가입했고, provider.tf 에 access_key 와 secret_key 를 세팅하니 terraform plan -out "output" 는 넘어갔습니다.

3] terraform 버전은 무엇을 사용하고 계실까요?
--> terraform version 입력하니 Terraform v1.0.1 on darwin_amd64 라고 나옵니다.

m1의 경우 특정 버전 이상을 사용해야만 제대로 돌아가기도 합니다.

감사합니다.
